### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by glyph** [pybee/briefcase#1]
'nuff said

**Comment by freakboy3742** [comment]
Yup - completely agreed. The approach isn't quite as obvious under Windows as it is under OS/X, but Windows should absolutely be supported (as should Linux)

**Comment by latusrepo** [comment]
FYI - I'm going to make an attempt at Windows support.  (Glyph and I discussed this a couple of days ago)

**Comment by latusrepo** [comment]
BTW, I've written a separate Windows "freezer" - see https://github.com/latusrepo/wosnap .  I didn't try to integrate it with anything else since I think it's rather ugly.  But it works for my historically difficult app that uses things like PySide and cryptography.

**Comment by glyph** [comment]
@latusrepo - wow, this is pretty cool. would it make sense for Briefcase to be a "front-end" to wosnap, to provide a consistent interface with other platforms, but just call into wosnap to do the actual freezing?

**Comment by latusrepo** [comment]
Sure, I can work on that.  I'll give it a go before the next SF Python project night, if not sooner. :)

**Comment by brechtm** [comment]
You might want to look at [pynsist](/takluyver/pynsist) or even cooperate with the author. It does a great job at creating an installer which bundles the Python interpreter and stdlib.

pynsist requires specifying the dependencies manually. It would be nice of it could use pip to resolve dependencies automatically, like briefcase does.

I'm not familiar with wosnap or osnap, but I'll check it out.

**Comment by jamesabel** [comment]
Yes, [osnap](https://github.com/jamesabel/osnap) is what I'm developing now (wosnap was an experiment that's now deprecated).  If you have any problems with osnap feel free to open an issue or message me.  Yes I know Thomas Kluyver - he's been a great help.  At some point we may want to incorporate osnap and/or pynsist into briefcase.  I know it's several months out, but perhaps we could sprint on this at PyCon if people are going.

**Comment by voltagex** [comment]
Consider this another +1 for Windows support in Briefcase. I found my way here via HackerNews and Briefcase (+beeware) seems like a really good approach to native apps with Python.

**Comment by johnscancella** [comment]
another +1. I would make a strong argument for use here at work except that most of our users use windows.

**Comment by flutefreak7** [comment]
Another +1, just heard about pyBee on reddit and since my current cx_freeze via esky setup is now obsolete (esky is unmaintained) I'm looking at the current scene wondering if I should try pyInstaller or something else. I'll have to check out osnap.

**Comment by jamesabel** [comment]
Hi @flutefreak7 - if you let me know what platforms are you targeting (e.g. Win, MacOS, etc.) and what package dependencies do you have (e.g. what's in your requirements.txt) I might be able to direct you to the appropriate tool.

**Comment by flutefreak7** [comment]
Targeting Windows, and dependant on pyside / PyQt, matplotlib, numpy, scipy, pandas, and other related libraries like seaborn, statsmodels, and pyqtgraph.

**Comment by jamesabel** [comment]
I'd suggest trying pynsist ( [https://pynsist.readthedocs.io](https://pynsist.readthedocs.io) ).  But eventually I hope we get all of that functionality into briefcase. :)  BTW, here's my tiny but effective test case for freezers/installers: [https://github.com/jamesabel/spafit](https://github.com/jamesabel/spafit)
