### ISSUE TITLE
Hashlib lacks 'ripemd160' even though included libSSL provides it

### ISSUE THREAD

**Issue by cculianu** [pybee/briefcase#100]
Any chance you guys can build python with the cpython .so stuff included so that hashlib picks up the 'ripemd160' hashing algorithm?

I need this algorithm to be available from the Python provided by HashLib.. but it isn't.

I'm porting Electron Cash to iOS.. which is why I ask.  

Otherwise great work guys!

**Comment by freakboy3742** [comment]
If it's just a configuration option for OpenSSL that isn't turned on by default, then it's certainly possible; ripemd160 wasn't explicitly excluded to the best of my knowledge. 

However, BeeWare is a volunteer project, and this isn't a personal priority for me; however, if you can do the ground work and work out how to modify the configure command for openSSL to include ripemd160, then I'll gladly integrate that into the [Python Apple support package](https://github.com/pybee/Python-Apple-Support).

**Comment by cculianu** [comment]
Ok, I'll play around with that github package and see what I can come up with.  Maybe it's something easy.  I didn't realize that repository existed.  Thanks for pointing me in the right direction...

**Comment by cculianu** [comment]
Ok, got it.  Something was missing from Setup.embdedded

By the way -- nice little auto-build system you got here.  I'm impressed.  You're helping the community tremendously with these tools!

I'll submit a PR shortly.

**Comment by cculianu** [comment]
I submitted the PR.  I'm closing this issue here and hopefully you will merge my PR at some point. 👍
