### ISSUE TITLE
windows app icon

### ISSUE THREAD

**Issue by hdm-dt-fb** [pybee/briefcase#103]
Sorry for this low-priority question, but I felt others might have this question too:
In the docs I found how to add the icon (as in snippet below) - this integrates very 
nicely into the installer and the windows start menu shortcut for the app.
(feels very native! btw: my platform windows7 python3.6)

However once the app is started, I get a generic symbol (I saw this icon in some 
other .net forms as well) on the left top (as in screenshot below) that also appears 
in the app switcher (alt-tab).

Is there already a way to use my provided icon there as well?
(Sorry, in case I missed something obvious.)

```python
    options={
        'app': {
            'formal_name': 'outlook_mail_exporter',
            'bundle': 'com.outlookmailexporter',
            'icon': 'images/icon',
        },
```

![image](https://user-images.githubusercontent.com/25063748/36304216-1bfa5e5c-130f-11e8-89df-6ddff1e195fa.png)

**Comment by hdm-dt-fb** [comment]
Hi @andrewleech thank you so much for the quick response! 
So far I was on the stable version from pypi (0.2.15) but I will 
dig into #75 to see if I can get it to work with the setuptools launchers..

**Comment by hdm-dt-fb** [comment]
Hi @andrewleech I made a virtual env, installed briefcase from git repo and also the brand new toga 0.3.0.dev5. When I bundle it via `python setup.py windows -s` pythonw crashes (when the bundler tries to run the app I assume), but nevertheless the installer gets built installs fine and runs.
The icon unfortunately is still the generic version as in the screenshot above.

**Comment by obulat** [comment]
You used Toga to create your app, didn't you? Toga winforms doesn't yet have Icon implementation.

**Comment by obulat** [comment]
@andrewleech  A newly-merged PR should solve this issue. Could you please check?
