### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by jedie** [pybee/briefcase#109]
What's about a docker image for "easy" start?

**Comment by andrewleech** [comment]
Are you thinking of docker image as a way of distributing your app, or for building your app with briefcase?

If you're talking about using docker to build your app, well you don't really need much. 

Here's one example, mostly complete: https://gitlab.com/alelec/hello_briefcase
https://gitlab.com/alelec/hello_briefcase/blob/master/.gitlab-ci.yml

Any generic Linux image with python will install and run briefcase quite easily. 
Windows, I've got a docker image with python and Wix installed used by that project, anyone is free to reuse that. 
Mac/iOS, doesn't have native docker so out of luck there. 
Android, yes it might be handy to extend an image with the android build tools to also include python and briefcase. 

If on the other hand you're thinking of using briefcase to build a docker image with your app as a new target type.... Yep not a bad direction... It's a valid alternative to snappy or flatpack to bundle dependencies for headless Linux apps that don't use the GUI.

**Comment by jedie** [comment]
Hm. Sorry. Wrong repro: I should have opened it better under https://github.com/pybee/batavia ;)
