### ISSUE TITLE
can't build for linux

### ISSUE THREAD

**Issue by onrkrt** [pybee/briefcase#116]
I am working on ubuntu 16.04 and get this error

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-bl78bqn7-build/

**Comment by andrewleech** [comment]
Hi,
It's unfortunate your getting an error, a bit more information will be needed to help though. 
Have you installed any different version of python than the one that came with Ubuntu?
What was the exact command you tried to run to install briefcase?
Could you provide all the text that was printed out for the command you ran, not just the last error line?
Thanks.

**Comment by danyeaw** [comment]
@onrkrt As @andrewleech said, we are going to need some more information to help troubleshoot this. If you have the detailed information on what your setup is, and the detailed step by step actions you did to get this error, then please open a new issue.
