### ISSUE TITLE
Tutorial 1 - ValueError: underlying buffer has been detached

### ISSUE THREAD

**Issue by rkabealo** [pybee/briefcase#135]
I'm trying to run the Tutorial 1 - Fahrenheit to Celsius (https://briefcase.readthedocs.io/en/stable/tutorial/tutorial-1.html) application for Android on Windows using Briefcase. It generates an android project, but when I try to load that onto the phone it's missing all the Toga widgets. 

I followed the instructions from Getting Started and Tutorial 0 (with the app name, "helloworld"). 

**Steps followed for Tutorial 0:** 
* Created a virtual environment
* Installed Briefcase
* Installed Cookiecutter
* Grabbed the template from the Github
* Ran setup.py

Runs fine on the phone. So I followed the same steps to create an entirely new project (app name, "ftoc") and replaced the code in app.py with the code in the Tutorial 1 instructions. Tried to run this one. This generates a ValueError in the command window:

```
(env) C:\Users\rkabealo\BeeWare\ftoc\ftoc>python setup.py android
running android
 * Writing application template...
Template Python-Android-template succesfully updated.
Project template: C:\Users\rkabealo/.cookiecutters/Python-Android-template
 * All libs are already copied
 * Determining best support package...
 * Installing support package...
Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Android-support/3.5/Android/Python-3.5-Android-support.b5.tar.gz
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django==0.3.0.dev8',
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\rkabealo\AppData\Local\Programs\Python\Python35\Lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\rkabealo\AppData\Local\Programs\Python\Python35\Lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\rkabealo\AppData\Local\Programs\Python\Python35\Lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\briefcase\app.py", line 459, in run
    self.install_platform_requirements()
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\briefcase\app.py", line 286, in install_platform_requirements
    ] + self.app_requires
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\pip\_internal\__init__.py", line 232, in main
    cmd_name, cmd_args = parseopts(args)
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\pip\_internal\__init__.py", line 172, in parseopts
    parser = create_main_parser()
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\pip\_internal\__init__.py", line 144, in create_main_parser
    'formatter': UpdatingDefaultsHelpFormatter(),
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\pip\_internal\baseparser.py", line 25, in __init__
    kwargs['width'] = get_terminal_size()[0] - 2
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\site-packages\pip\_internal\compat.py", line 204, in get_terminal_size
    return tuple(shutil.get_terminal_size())
  File "C:\Users\rkabealo\BeeWare\ftoc\env\lib\shutil.py", line 1062, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
ValueError: underlying buffer has been detached
```

It also generates an android project. When I tried to load that android project into IntelliJ and run it on the phone, it loads the exact same thing as Tutorial 0 (just with a title of "ftoc" instead of "helloworld"). None of the Toga widgets show up: no bars to put numbers in, no buttons, etc. The actual generated PythonActivity.java files for both Tutorial 0 and Tutorial 1 are exactly the same, minus the difference in name. 

I'd understand if Tutorial 1 didn't work at all or if it worked flawlessly. But the fact that it's only missing the Toga widgets is what's confusing me. 

So I guess this is a two part problem:  
1) How do I fix the ValueError error? 
2) Is the ValueError related to the missing Toga widgets?

**Attempts at fixing the issue:** 
- Explicitly installing Toga (0.3) in the virtual environment using pip install 
- Downgrading to Toga version 0.2.15 
- Downgrading VOC to version 1.4 (from 1.5) 

**Information:**
- OS version: Windows 10 Pro 
- Python: 3.5.0 (virtualenv)
- Phone: Samsung Galaxy S8, Android 7.0 (Nougat)
- Software: IntelliJ Idea 
- Java: 10.0.1 

**Other info:** 
```
pip freeze
arrow==0.12.1
binaryornot==0.4.4
boto3==1.7.32
botocore==1.10.32
briefcase==0.2.4
certifi==2018.4.16
chardet==3.0.4
click==6.7
colosseum==0.1.6
cookiecutter==1.6.0
docutils==0.14
future==0.16.0
idna==2.6
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
MarkupSafe==1.0
poyo==0.4.1
python-dateutil==2.7.3
pythonnet==2.3.0
requests==2.18.4
s3transfer==0.1.13
six==1.11.0
toga==0.2.15
toga-core==0.2.15
toga-winforms==0.2.15
urllib3==1.22
voc==0.1.4
whichcraft==0.4.1
```

Any help would be much appreciated!

**Comment by freakboy3742** [comment]
That's definitely an odd error. My guess is that it's actually a bug in your IDE, not Briefcase - the error is being raised deep in the code for pip, when pip is trying to establish the size of the terminal screen so it can display a progress bar when downloading. There's not much we can do there - your IDE's "terminal" isn't a fully compliant TTY, and as a result, the installation process is crashing.

That said - the 0.3.0 branch is currently in development (hence the dev8 suffix), and Android is one of the backends where we know there is work to be done. So, even if you used a "normal" terminal, rather than an IDE, you're going to have problems. 

The 0.2.15 tutorial is known to work on Android; there are some subtle changes in API between the two versions, so you'll need to "downgrade" your code before it will work.
