### ISSUE TITLE
Making a new Briefcase iOS project has the wrong Bundle ID in the generated project

### ISSUE THREAD

**Issue by cculianu** [pybee/briefcase#138]
I used setup.py ios to make an iOS project (my setup.py is attached).

It works great.  In fact, we're getting ready to release to the store. 

Only one issue has been a pet peeve for 5 months now that I've been working on this.  I have been too busy to write you guys about it but perhaps you can easily fix it.  The generated iOS project has the correct bundle identifier for "Release" builds, but uses TravelTips bundle identifier for the "Debug" builds.  This makes me crazy as I have to remember to change it back each time.

Did I do something wrong?  Or is this just a bug/oversight in Briefcase?

Attached are some screenshots to show you what I'm talking about, plus my setup.py (in case I did something wrong?)

<img width="419" alt="screen shot 2018-06-13 at 2 58 44 am" src="https://user-images.githubusercontent.com/266627/41323290-35cb6e0e-6eb6-11e8-9a01-50a2913e2aad.png">
<img width="708" alt="screen shot 2018-06-13 at 2 58 56 am" src="https://user-images.githubusercontent.com/266627/41323291-37a948fe-6eb6-11e8-9640-15ec9d656231.png">

[setup.txt](https://github.com/pybee/briefcase/files/2096178/setup.txt)

**Comment by freakboy3742** [comment]
/me looks 🐑 ish...

You weren't doing anything wrong - that was all my doing. I've now corrected the problem in the briefcase template.
