### ISSUE TITLE
ios - NameError: name 'LEFT' is not defined

### ISSUE THREAD

**Issue by cepages** [pybee/briefcase#139]
When running the simple helloworld tutorial on OSX, i get the error when running the command

```python3 setup.py ios -s```

When I run the second tutorial ( https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-1.html ) the app starts but it crashes with: 

```
line 26, in startup
    self.c_label = toga.Label('Celcius', style=Pack(text_align=LEFT))
NameError: name 'LEFT' is not defined
```

I tried in iOS 11 and iOS 10.3.1

**Comment by freakboy3742** [comment]
I can only assume that the source code you've copied over is incomplete - you couldn't the error you describe if you've got a complete copy of the tutorial-1 code. Tutorial-1 imports the symbol LEFT on line 3.
