### ISSUE TITLE
Support package version comparison breaks with versions > b9

### ISSUE THREAD

**Issue by freakboy3742** [pybee/briefcase#146]
When determining the support package to use (in `briefcase/app.py`, function `find_support_pkg()`), the code looks to S3, finds all matching support packages, reverse sorts them, and then returns the first item.

This is an alphabetical sort, based on filename.

A support package has a name matching the pattern `Python-3.7-macOS-support.b1.tar.gz` (for Python 3.7, build 1)

Alphabetical sorts will work fine for builds 1-9... but build 10 will appear alphabetically between b1 and b2.

We need to split the filename to extract the build number, and then sort numerically.

**Comment by irulenot** [comment]
I read somewhere i'm supposed to comment if i'm going to try to fix it. Is that accurate? Anyway, i'm looking into it!

**Comment by rayrrr** [comment]
I claim this issue.
