### ISSUE TITLE
Execution failed for task ':transformClassesWithDexForDebug' while trying to build tutorial 0 for android

### ISSUE THREAD

**Issue by sparky005** [pybee/briefcase#153]
Hello! I'm trying to follow tutorial 0 with the aim of building a python app for android. Unfortunately, when I run ```python setup.py android -s``` I get an error during the build. I keep running into something like this:
```
* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
```
I googled around and saw some suggestions of adding ```multiDexEnabled true``` to my build.gradle, but this fix didn't work for me. Any ideas? Full build log attached. Thank you!

[output.txt](https://github.com/pybee/briefcase/files/2237663/output.txt)

**Comment by sparky005** [comment]
It looks like I was able to resolve the issue by changing the toga version to 0.2.5 in ```setup.py```. Am I doing something wrong that I have to fix that?

**Comment by freakboy3742** [comment]
The issue is that Toga 0.3.0 hasn't been fully updated to support Android. There are also some issues with the VOC compiler supporting some of the changes that have been introduced in the 0.3.0 branch.

In the meantime, using Toga 0.2.15 for Android is the best option.

**Comment by sparky005** [comment]
Thanks @freakboy3742. I had to downgrade toc to version 0.1.4 as well. 

I used the cookiecutter to create the project template as the tutorial specified. The cookiecutter is what chose the version for me. Should the tutorial be changed? Right now it's leading people to broken setups, which I imagine will cause more people like me to create issues like this.

**Comment by Dev-loper0** [comment]
How I can downgrade voc to version 0.1.4
