### ISSUE TITLE
  Failed building wheel for pygobject

### ISSUE THREAD

**Issue by bmsleight** [pybee/briefcase#176]
Solved: apt-get install libcairo2-dev

Log 1 (without libcairo2-dev):-

$ python setup.py linux -s
running linux
 * Writing application template...
Template Python-Linux-template succesfully updated.
Project template: /home/bms/.cookiecutters/Python-Linux-template
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-gtk==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/00/17/198a9d0eb0e89b5c7d2a9b4437eb40d62702ab771030cd79fc7141cb0d30/PyGObject-3.30.1.tar.gz
Collecting gbulb>=0.5.3 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/92/cb/d2a0e4899cde5aa797e31d77a0a7422dcd188d880bb38d0e9d1b1196e5c6/gbulb-0.6.1.tar.gz
Collecting toga-core==0.3.0.dev11 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Building wheels for collected packages: pycairo, pygobject, gbulb
  Running setup.py bdist_wheel for pycairo ... done
  Stored in directory: /home/bms/.cache/pip/wheels/96/d7/27/11325e387f45d69372212d0da63c366fe0db450c2cab978ad2
  Running setup.py bdist_wheel for pygobject ... error
  Complete output from command /home/bms/Documents/beeware/tutorial/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pofjqzfa/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-c5py3_9_ --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.5/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.5/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.5/pygtkcompat
  creating build/lib.linux-x86_64-3.5/gi
  copying gi/module.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/importer.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/types.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_option.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_error.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_compat.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.5/gi
  creating build/lib.linux-x86_64-3.5/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.5/gi/repository
  creating build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.5/gi/overrides
  running build_ext
  pycairo: new API
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1189, in <module>
      main()
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1184, in main
      zip_safe=False,
    File "/home/bms/Documents/beeware/tutorial/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/bms/Documents/beeware/tutorial/venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1024, in run
      self._setup_extensions()
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1019, in _setup_extensions
      add_pycairo(gi_cairo_ext)
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1003, in add_pycairo
      ext.include_dirs += [get_pycairo_include_dir()]
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 832, in get_pycairo_include_dir
      include_dir = find_path(find_new_api())
    File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 777, in find_new_api
      import cairo
  ImportError: No module named 'cairo'
  
  ----------------------------------------
  Failed building wheel for pygobject
  Running setup.py clean for pygobject
  Running setup.py bdist_wheel for gbulb ... done
  Stored in directory: /home/bms/.cache/pip/wheels/92/57/1e/d484f762cdd6b5a1e737517f4e2d122ba261544a7e615f2269
Successfully built pycairo gbulb
Failed to build pygobject
Installing collected packages: pycairo, pygobject, gbulb, travertino, toga-core, toga-gtk
  Running setup.py install for pygobject ... error
    Complete output from command /home/bms/Documents/beeware/tutorial/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pofjqzfa/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_kv55ux5/install-record.txt --single-version-externally-managed --compile --install-headers /home/bms/Documents/beeware/tutorial/venv/include/site/python3.5/pygobject --home=/tmp/pip-target-skq1oty3:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pygtkcompat
    copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.5/pygtkcompat
    copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.5/pygtkcompat
    copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.5/pygtkcompat
    creating build/lib.linux-x86_64-3.5/gi
    copying gi/module.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/importer.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_constants.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/types.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/docstring.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/__init__.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_option.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_error.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_compat.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.5/gi
    creating build/lib.linux-x86_64-3.5/gi/repository
    copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.5/gi/repository
    creating build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.5/gi/overrides
    running build_ext
    pycairo: new API
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1189, in <module>
        main()
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1184, in main
        zip_safe=False,
      File "/home/bms/Documents/beeware/tutorial/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/bms/Documents/beeware/tutorial/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1024, in run
        self._setup_extensions()
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1019, in _setup_extensions
        add_pycairo(gi_cairo_ext)
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 1003, in add_pycairo
        ext.include_dirs += [get_pycairo_include_dir()]
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 832, in get_pycairo_include_dir
        include_dir = find_path(find_new_api())
      File "/tmp/pip-install-pofjqzfa/pygobject/setup.py", line 777, in find_new_api
        import cairo
    ImportError: No module named 'cairo'
    
    ----------------------------------------
Command "/home/bms/Documents/beeware/tutorial/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pofjqzfa/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_kv55ux5/install-record.txt --single-version-externally-managed --compile --install-headers /home/bms/Documents/beeware/tutorial/venv/include/site/python3.5/pygobject --home=/tmp/pip-target-skq1oty3" failed with error code 1 in /tmp/pip-install-pofjqzfa/pygobject/
 * Installing project code...
Processing /home/bms/Documents/beeware/tutorial/helloworld
Building wheels for collected packages: helloworld
  Running setup.py bdist_wheel for helloworld ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-gjlqqwmi/wheels/b4/f7/9f/6acfcfb5c66d1d4a715c037753ab88acc881464fa149c628c6
Successfully built helloworld
Installing collected packages: helloworld
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Hello World
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bms/Documents/beeware/tutorial/helloworld/linux/app/helloworld/__main__.py", line 1, in <module>
    from helloworld.app import main
  File "/home/bms/Documents/beeware/tutorial/helloworld/linux/app/helloworld/app.py", line 2, in <module>
    import toga
ImportError: No module named 'toga'

App started.

Log 2 (with libcairo2-dev):-

$ python setup.py linux -s
running linux

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-gtk==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/00/17/198a9d0eb0e89b5c7d2a9b4437eb40d62702ab771030cd79fc7141cb0d30/PyGObject-3.30.1.tar.gz
Collecting toga-core==0.3.0.dev11 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting gbulb>=0.5.3 (from toga-gtk==0.3.0.dev11)
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11)
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Building wheels for collected packages: pygobject
  Running setup.py bdist_wheel for pygobject ... done
  Stored in directory: /home/bms/.cache/pip/wheels/78/0f/04/3513cf50133cbc553ad5e83e37009b76231ab0e0f62bd8527f
Successfully built pygobject
Installing collected packages: pycairo, pygobject, travertino, toga-core, gbulb, toga-gtk
Successfully installed gbulb-0.6.1 pycairo-1.17.1 pygobject-3.30.1 toga-core-0.3.0.dev11 toga-gtk-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /home/bms/Documents/beeware/tutorial/helloworld
Building wheels for collected packages: helloworld
  Running setup.py bdist_wheel for helloworld ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-29uqw4gy/wheels/b4/f7/9f/6acfcfb5c66d1d4a715c037753ab88acc881464fa149c628c6
Successfully built helloworld
Installing collected packages: helloworld
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Hello World
[GTK+] Not implemented: Widget.set_hidden()

App started.

**Comment by bmsleight** [comment]
apt-get install libcairo2-dev

**Comment by jrborbars** [comment]
Installing pycairo does not solve the problem (for me). I need to install gobject-introspection in manjaro, too. In Ubuntu based systems maybe installing libgirepository1.0-dev can help.

**Comment by cr105ph1nx** [comment]
@jrborbars Thank you! gobject-introspection was what I was missing for it to work on ArchOS

**Comment by debian-user-france1** [comment]
Still doesn't work on my manjaro

**Comment by leonardoapolinario** [comment]
> Installing pycairo does not solve the problem (for me). I need to install gobject-introspection in manjaro, too. In Ubuntu based systems maybe installing libgirepository1.0-dev can help.

Thank you. It works on Ubuntu 20.04.4

**Comment by freakboy3742** [comment]
@KajeArch The CI logs on this repository prove that you can, in fact, "compile a single program". 

I'd love to be able to help you - but you've chosen to *not* provide any details that might help me do so. If you want help diagnosing a problem, we're going to need details on the problem you're having.
