### ISSUE TITLE
MacOs Simulator fails to launch

### ISSUE THREAD

**Issue by DannyCork** [pybee/briefcase#187]
Hi,
I'm running Mac OS 10.14.2 (18C54) and following the tutorial.

I've observed that when running 
**$ python setup.py ios -s**

simulator doesn't open:
`
$ python3.7 setup.py ios -s
running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/36/f1/a5e2f2390b3129768e2399d6c8a2e5ef3ffb2bf82f4e5e33b6bf7842dc7d/toga_iOS-0.3.0.dev11-py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting rubicon-objc>=0.3.0 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/ce/55/b7fbfd72cbd3d18322d94305179c6c1805fe4b5e10619d6954adf7f1d6a3/rubicon_objc-0.3.0-py2.py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: travertino, toga-core, rubicon-objc, toga-ios
Successfully installed rubicon-objc-0.3.0 toga-core-0.3.0.dev11 toga-ios-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /Users/x/pythonGui/helloworld
Installing collected packages: helloworld
  Running setup.py install for helloworld ... done
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Building for iOS 12.1...

Available devices:
  [1] iPhone 5s
  [2] iPhone 6
  [3] iPhone 6 Plus
  [4] iPhone 6s
  [5] iPhone 6s Plus
  [6] iPhone 7
  [7] iPhone 7 Plus
  [8] iPhone 8
  [9] iPhone 8 Plus
  [10] iPhone SE
  [11] iPhone X
  [12] iPhone XS
  [13] iPhone XS Max
  [14] iPhone XR
  [15] iPad Air
  [16] iPad Air 2
  [17] iPad (5th generation)
  [18] iPad Pro (9.7-inch)
  [19] iPad Pro (12.9-inch)
  [20] iPad Pro (12.9-inch) (2nd generation)
  [21] iPad Pro (10.5-inch)
  [22] iPad (6th generation)
  [23] iPad Pro (11-inch)
  [24] iPad Pro (12.9-inch) (3rd generation)
Which device do you want to target: 10
 * Building XCode project for iPhone SE iOS 12.1...

Build complete.

Starting app on iPhone SE iOS 12.1
 * Starting simulator...
instruments[3373]: Waiting for device to boot...
 * Uninstalling old app version...
 * Installing new app version...
 * Launching app...
`

**Simulator fails to open. If I launch Simulator manually , the compiled app is there waiting to be run.**
**Watching the console I can see relevant error messages**

`
default	23:38:13.111310 +0000	CoreSimulatorBridge	Got application not found error for 'com.example.Hello-World'.

default	23:38:13.111575 +0000	CoreSimulatorBridge	Skipping reinstall of com.example.Hello-World (com.example.helloworld 

file:///Users/d/pythonGui/helloworld/iOS/build/Debug-iphonesimulator/Hello20World.app/ {
    CFBundleIdentifier = "com.example.helloworld";
    PackageType = Developer;

    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot";
    SimulatorUserPath = "/Users/d/Library/Developer/CoreSimulator/Devices/3630378B-8DC0-417B-B375-602E974A738D/data";

}).
default	23:38:13.111846 +0000	CoreSimulatorBridge	Launch attempt #5 for bundle 'com.example.Hello-World', have been trying to launch for 54 seconds. Modern launch services = YES
default	23:38:13.112094 +0000	CoreSimulatorBridge	Failed to get LSBundleProxy for 'com.example.Hello-World'
default	23:38:13.112258 +0000	CoreSimulatorBridge	[FBSSystemService][0x8caf] Sending request to open "com.example.Hello-World"
error	23:38:23.705926 +0000	CoreSimulatorBridge	[FBSSystemService][0x8caf] Error handling open request for com.example.Hello-World: <NSError: 0x7fde00c5a2a0; domain: FBSOpenApplicationServiceErrorDomain; code: 1 (RequestDenied); reason: "The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.example.Hello-World" is unknown to FrontBoard")."> {
    description = "The request to open "com.example.Hello-World" failed.";
    failureReason = "The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.example.Hello-World" is unknown to FrontBoard").";
    userInfo = {
        FBSOpenApplicationRequestID = <__NSCFNumber: 0xed0a0989269e13b5>;
    }
    underlyingError = <NSError: 0x7fde00c58470; domain: FBSOpenApplicationErrorDomain; code: 4 (NotFound); reason: "Application "com.example.Hello-World" is unknown to FrontBoard."> {
        description = "The operation couldn’t be completed. Application "com.example.Hello-World" is unknown to FrontBoard.";
        failureReason = "Application "com.example.Hello-World"
default	23:38:23.706147 +0000	CoreSimulatorBridge	Error Launching: Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.example.Hello-World" failed." UserInfo={NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.example.Hello-World" is unknown to FrontBoard")., BSErrorCodeDescription=RequestDenied, NSUnderlyingError=0x7fde00c58470 {Error Domain=FBSOpenApplicationErrorDomain Code=4 "Application "com.example.Hello-World" is unknown to FrontBoard." UserInfo={BSErrorCodeDescription=NotFound, NSLocalizedFailureReason=Application "com.example.Hello-World" is unknown to FrontBoard.}}, FBSOpenApplicationRequestID=36015, NSLocalizedDescription=The request to open "com.example.Hello-World" failed.}
`

**Comment by ikelca** [comment]
Go to edit source code of iOS.py  in briefcase folder and find line for `print(' * Starting `simulator...')' and change what's inside subprocess.popen to the following: 
`print(' * Starting simulator...')
        subprocess.Popen(
            ['open', '-a','Simulator','--args','-CurrentDeviceUDID', self.device['udid']],
            stderr=subprocess.PIPE
        ).communicate()`


save it and you should be able to start simulator now.

**Comment by freakboy3742** [comment]
FYI I've just released v0.2.9 that implements the change described by @ikelca.
