### ISSUE TITLE
Support for 2.7 ? 

### ISSUE THREAD

**Issue by Marini83** [pybee/briefcase#193]
So https://github.com/pybee/Python-iOS-template/tree/2.7  points that 2.7 is supported, however briefcase does not.  Does Briefcase support 2.7 or not?

**Comment by freakboy3742** [comment]
Briefcase does not support Python 2 (at least, not any more). 

At one point it did, but we dropped that support a while back, due to the impending EOL of Python 2.

**Comment by Marini83** [comment]
Thank you @freakboy3742
