### ISSUE TITLE
Add check for pre-existing application directory

### ISSUE THREAD

**Issue by freakboy3742** [pybee/briefcase#25]
If you have an existing macOS directory, and you run `python setup.py macos`, you get a messy error message about a directory already existing. The same is true for other platform directories.

It would be better to replace this with a check - "do you want to replace this project y/n", and if y, delete the existing directory before regenerating.

**Comment by eliasdorneles** [comment]
This was fixed in https://github.com/pybee/briefcase/commit/686fd652c383c8f4bbcb1fba77c2b3797435627f
