### ISSUE TITLE
[Specification] Windows project template

### ISSUE THREAD

**Issue by freakboy3742** [pybee/briefcase#30]
# Abstract

Develop a Visual Studio 2017 solution file that will enable a user to download a zip file of content (including a solution file), open the solution, hit run, and have the code Just Work (tm).

## Full description

Python.net contains an example project that shows how to embed a Python interpreter into a C# project. However, this project doesn't work "out of the box" - it requires a bunch of configuration before it will work. It is part of a larger project, so you need to modify the solution file to set the starting project; then, when you do run it, you get errors because Python27.dll can't be found - which is problematic if you're trying to use Python 3.5.

I want to be able to give someone a zip file that contains the solution file and source code, have them open the file, run it, and get a useful executable.

The deliverable is the zip file, containing a Visual Studio 2017 solution file, the C# source code from the Python.net console demo, and any other support files necessary. I imagine this will include:

A copy of Python. The zip file should contain the official embedded python zip file in a known location relative to the solution file. However, you cannot depend on a system installation of Python (or anything else other than Visual Studio).
An installation of Python.net. Ideally, this will be in a directory other than the site-packages provided by the embedded Python install
When compiled, the executable should have a custom icon; any icon will do for sample purposes, but it should also be available in the zip file.

The ideal layout for the final zip file would be:

* Windows 
  - MyProject.sln 
  - MyProject.cs 
  * MyProject
    * Resources 
      - myproject.ico
    * Python 
      - (contents of embedded Python zip file)
    * app_packages 
      - (installed version of python.net)
    * app 
      * MyProject
        - `__init__.py`
        - `app.py`

The solution file should output "MyProject.exe" in the MyProject directory.

## Bonus points

For bonus points:

1. The default source from the console demo of Python.net will require a command line argument; modify the sample code to invoke app.py with the contents of app and app_packages in the PYTHONPATH for the purposes of execution.

2. The output app should be a gui app, not a console app. When MyProject.exe is executed, a black console window should not be displayed.

3. Add a target to the solution file that produces an MSI installer with contents of the "MyProject" directory, including the executable, embedded python, app_packages and app.

**Comment by denfromufa** [comment]
I replied on Twitter: 

Denis Akhiyarov (@denfromufa) Tweeted:
@PyBeeWare The pythonnet.sln is actually configured by setup.py during build step. I recommend this troubleshooting wiki: https://t.co/K7oUdIsAQp https://twitter.com/denfromufa/status/852717207247368193?s=17

**Comment by denfromufa** [comment]
You can grab nuget packages for pythonnet and Python to embed them in a C# project. This hasn't been documented or tested yet:

https://github.com/Microsoft/PTVS/issues/2304

**Comment by denfromufa** [comment]
I can't help on the MSi installer (perhaps pynsist or constructor?). But here is how to hide console in c#:

http://stackoverflow.com/a/3571628/2230844

**Comment by NathanW2** [comment]
Maybe wix for the MSI installer?

**Comment by denfromufa** [comment]
@NathanW2 You can certainly use wix for building full-blown MSI installers, like the original CPython installer:

https://github.com/python/cpython/tree/master/Tools/msi

But this requires some knowledge of wix. That's why I suggested pynsist or constructor, both based on nsis.

Anyway the installer is secondary, the primary issue here is how to include cpython in pythonnet solution and build it into stand-alone application.

I also did not understand why @freakboy3742 picked VS 2017 - it still has a lot of churn with Python. I would recommend waiting for next update and use VS 2015 in the meantime.

But main issue I have is *WHY do you need to embed CPython in C#*?

**Comment by freakboy3742** [comment]
1. I didn't pick NSIS because I want a proper MS Installer, not just an installer-like tool. One of the guiding principles of the BeeWare suite is to build tools that are indistinguishable from native tools. Part of that is an installation process that is as native as possible as well. From everything I've read, NSIS installers don't meet that requirement, because they don't fit into the transactional installation process Windows provides.

2. I picked VS2017 because that's what you get when you go to the Microsoft website. If there's a better option, I'm all ears.

3. What I'm trying to do is provide an artefact on disk that can be used to start a Toga application. cx_freeze and pyinstaller aren't options because they depend on the existence of system Python installation. I want a completely isolated standalone installer that works when I just give you *just* the application installer. The approach I want to use is much the same as I'm using on iOS - a bare bones compiled executable that is a bootstrap to start the Python interpreter and start the app. This lets you attach an icon to the executable, and if you ship the embedded Python library, you've got an isolated, standalone environment.

On top of all of this, Windows isn't my platform of choice, I haven't touched Visual Studio in almost 15 years, and haven't much C# at all - none of it on Windows. I've tried to pull apart the "console" example, but it's intertwined with a bunch of other stuff in the PythonNet project, isn't easily isolated, and obviously requires some sort of pre-configuration (which AFAICT isn't documented anywhere). I tried the "just drop the PythonNet library into a new project" approach, and then spent the next couple of hours debugging an error that turned out to be related to the fact that the default project targets MSIL, but PythonNet is targeted at x64 (which I can only assume is Windows-speak for x86-64). I'm up against a time deadline, so I was hoping for someone to crack this nut as an interesting but simple problem if you *are* a domain expert, rather than having to spend a couple of weeks learning how to drive Visual Studio again. 

Filling in some extra context - eventually, after a couple of days getting no progress, I gave up on the idea of using an executable and switched to trying to use a batch/command script starting the python executable that ships with the embedded Python installer. However, that failed because the embedded interpreter doesn't honour PYTHONPATH (by design). Hence my question about whether there was any way to pass in PYTHONPATH. 

I have found *a* solution - using Powershell to generate a shortcut link - but AFAICT, it's not relocatable, and the icon has the shortcut overlay on it. It's not ideal, but it "works", for some definition of work. But again - Windows isn't my platform of choice, and I'm up against a deadline, so this will have to do for now. 

If someone wants to provide an alternative - like what I've described in this ticket, or anything better - I'll happily integrate it.

**Comment by NathanW2** [comment]
If I get some time I can help you with wix at least. I have just done it
for qgis to make MSI packages.

**Comment by NathanW2** [comment]
> cx_freeze and pyinstaller aren't options because they depend on the
existence of system Python installation

What do you mean by this.  They are only required on the dev machine. Once
you use cx_freeze you should have a standalone app.  I have used py2exe in
the past but it's the same idea.

**Comment by freakboy3742** [comment]
@NathanW2 I must have been doing something wrong then, because I'm fairly sure from my experimentation that cx_freeze ended up putting files in my system (well, venv) Python install.

**Comment by NathanW2** [comment]
Shouldn't do from what I know. It should just give you a standalone exe
with no need for anything else.

**Comment by freakboy3742** [comment]
This was resolved and released in v0.2.0
