### ISSUE TITLE
open marketplace for pybee apps based on briefcase

### ISSUE THREAD

**Issue by denfromufa** [pybee/briefcase#32]
@freakboy3742 I noticed that you are exploring ways to fund pybee (beeware) development. So why not open a marketplace? This is where developers can easily deploy their apps on multiple devices and consumers can easily get them on their platform. This can of course be integrated with existing app stores by providing a "runtime" which all apps can be built on top (e.g. like adobe air).

**Comment by freakboy3742** [comment]
Don't worry - various forms of marketplace have definitely occurred to me. The approach you've described sounds like you're proposing circumventing app stores, which is at best problematic on Apple platforms (Apple will reject apps that try to avoid their App Store as a distribution mechanism). 

However, there are definitely opportunities to monetize various parts of the development and distribution process. I'm interested in exploring these; however, at the moment, it's possibly a bit premature, especially considering the development effort that would be necessary to build a commercial platform to support tools that are well pre v1.0.

I'm going to close this ticket on the basis that there's nothing directly actionable right now. However, be assured that the idea (or some variation of it) is on our roadmap.

**Comment by denfromufa** [comment]
@freakboy3742 totally makes sense, I was not proposing to bypass existing app stores. Apple app store makes 28 bln. USD!
