### ISSUE TITLE
Avoid re-downloading the cookiecutter template if it's already downloaded

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/briefcase#36]
Currently, briefcase always re-downloads the cookiecutter template.

Since re-generating an application bundle (for example, running `python setup.py ios` or `python setup.py android`) is meant to be a very common thing to do, it would be nice if it tolerate network issues.

My suggestion is that we check if there is a template already downloaded, and if it does, instead of re-cloning it, we'd try updating it (running `git pull`) and just emit a warning in case updating fails.

**Comment by eliasdorneles** [comment]
Btw, not sure if this will need special handling, but the update shouldn't be tried if one specifies `--template`.

**Comment by freakboy3742** [comment]
Resolved by #39
