### ISSUE TITLE
Android App: problem occurred starting process 'command 'voc''

### ISSUE THREAD

**Issue by Ry10p** [pybee/briefcase#51]
Could be something that I am doing.... I am not very good at this yet....
but when i am trying to build the android app it gives me this in the android studio "output".

Executing tasks: [:generateDebugSources, :generateDebugAndroidTestSources, :mockableAndroidJar, :prepareDebugUnitTestDependencies]

Configuration on demand is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_2vatwc3kktfozgkt2xw3ajzcb.run(/home/ry/.MyShit/Native/BeeWare1/tutorial_0/android/build.gradle:11)
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/ry/.MyShit/SDK/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2511Library
:prepareComAndroidSupportAppcompatV72511Library
:prepareComAndroidSupportSupportCompat2511Library
:prepareComAndroidSupportSupportCoreUi2511Library
:prepareComAndroidSupportSupportCoreUtils2511Library
:prepareComAndroidSupportSupportFragment2511Library
:prepareComAndroidSupportSupportMediaCompat2511Library
:prepareComAndroidSupportSupportV42511Library
:prepareComAndroidSupportSupportVectorDrawable2511Library
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:preDebugAndroidTestBuild UP-TO-DATE
:prepareDebugAndroidTestDependencies
:compileDebugAndroidTestAidl UP-TO-DATE
:processDebugAndroidTestManifest UP-TO-DATE
:compileDebugAndroidTestRenderscript UP-TO-DATE
:generateDebugAndroidTestBuildConfig UP-TO-DATE
:generateDebugAndroidTestResValues UP-TO-DATE
:generateDebugAndroidTestResources UP-TO-DATE
:mergeDebugAndroidTestResources UP-TO-DATE
:processDebugAndroidTestResources UP-TO-DATE
:generateDebugAndroidTestSources UP-TO-DATE
:mockableAndroidJar UP-TO-DATE
:preDebugUnitTestBuild UP-TO-DATE
:prepareDebugUnitTestDependencies

BUILD SUCCESSFUL

Total time: 18.995 secs
Executing tasks: [:assembleDebug]

Configuration on demand is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_2vatwc3kktfozgkt2xw3ajzcb.run(/home/ry/.MyShit/Native/BeeWare1/tutorial_0/android/build.gradle:11)
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/ry/.MyShit/SDK/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2511Library
:prepareComAndroidSupportAppcompatV72511Library
:prepareComAndroidSupportSupportCompat2511Library
:prepareComAndroidSupportSupportCoreUi2511Library
:prepareComAndroidSupportSupportCoreUtils2511Library
:prepareComAndroidSupportSupportFragment2511Library
:prepareComAndroidSupportSupportMediaCompat2511Library
:prepareComAndroidSupportSupportV42511Library
:prepareComAndroidSupportSupportVectorDrawable2511Library
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileDebug
:compileDebugJavaWithJavac UP-TO-DATE
:compileDebugNdk NO-SOURCE
:compileDebugSources UP-TO-DATE
:buildPythonDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildPythonDebug'.
> A problem occurred starting process 'command 'voc''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.482 secs

**Comment by eliasdorneles** [comment]
Hm, the chances are that the `voc` command isn't available for the Python environment that Android Studio is using.
How exactly are you running the build? Can you tell exactly the steps you did for importing the project as well?

**Comment by Ry10p** [comment]
I have my .bashrc setup with the following from cordova...

export ANDROID_HOME=/Development/android-sdk/

export PATH=${PATH}:/Development/android-sdk/platform-tools:/Development/android-sdk/tools

source ~/.bash_profile

export ORG_GRADLE_PROJECT_cdvMinSdkVersion=20

Then I used the GUI provided from android studio to import thr gradle project.

Do I need a NDK also? I only have the SDK pathed...

**Comment by eliasdorneles** [comment]
I assume you generated this project using a virtualenv with Python 3, am I right?
I would guess that this error is because Android Studio isn't using the Python 3 from that virtualenv.

But you'd need to debug this further to know for sure.

Can you try activating the virtualenv, and then building from the command line, using `./gradlew build` inside the `android` directory?

**Comment by Ry10p** [comment]
Sir!

Thank you so much!

It worked I have generated an APK...

A further question... now that the apk is made how would i go about loading it into android studio or my phone?

When attempting to now bring the project into android studio I run int this:

Error:(58, 1) A problem occurred configuring root project 'android'.
> Could not get unknown property 'packageRelease' for root project 'android' of type org.gradle.api.Project.

Is there something I am not adding to the project?
OR
Is there a different way of uploading the file app onto the phone?

You are Amazing! Thank you for the time!
-Ryan Carl

**Comment by Ry10p** [comment]
@eliasdorneles 

Hello sir!
How do we complete the android process?
After the build I get an apk, but i'm not sure how to use it without android studio...
When attempting to now bring the project into android studio I run into this:

Error:(58, 1) A problem occurred configuring root project 'android'.

Could not get unknown property 'packageRelease' for root project 'android' of type org.gradle.api.Project.
Is there something I am not adding to the project?
OR
Is there a different way of uploading the file app onto the phone?

Also i have helped a person at this link that will be running into the same problem after the 
`./gradelw` build.
You are Amazing! Thank you for the time!
-Ryan Carl

**Comment by eliasdorneles** [comment]
If you have your phone connected as the Android device (or if you have an emulator running), it should be enough to run `./gradlew run` for the APK to load on it and start.

**Comment by Ry10p** [comment]
Thank you SO MUCH!!
@eliasdorneles You are amazing!

I hope it will be ok if add a tutorial for android projects on the main site....

Thank you so much again!
