### ISSUE TITLE
TOGA-GTK Porting Widgets: A few Questions

### ISSUE THREAD

**Issue by Ry10p** [pybee/briefcase#54]
Hello!

I am working on getting the widgets that haven't been implemented on Gtk, yet have been implemented on the Cocoa backend.  

Toga-gtk
https://github.com/pybee-attic/toga-gtk/tree/master/toga_gtk/widgets

Toga-Cocoa
https://github.com/pybee-attic/toga-cocoa/tree/master/toga_cocoa/widgets

**My question is, the script icon.py is found in both of the backends, yet the script image.py is not included in the toga-gtk backend.  Is there a reason for this? Are we using the icon as an image also?

If not, may I create this file and widget also? (maybe change the name if it is for all image uses)
OR
Are we using the "icons" as images also?**

-Thanks for teaching me & thank you for your time!
-Ryan Carl

**Comment by Ry10p** [comment]
@freakboy3742 
Hello Sir, 

I know you are busy and I don't want to bother you.  So please whenever you have a chance I could use some help...
 
I feel really dumb asking this question, but how do I go about testing the widgets that i have ported from Cocoa backend to the Gtk backend?

Thanks for helping!
-Ryan Carl

**Comment by freakboy3742** [comment]
Testing is an area that we're working on at the moment; there's a Google Summer of Code project underway at the moment that should hopefully result in a formal API that we can use for testing purposes.

In the meantime, the best way to test is to try and run the tutorial applications. Those tutorial applications are essentially drawn from experimentation around adding new widgets. If you can run the tutorials, your backend works.

If you wanted to formalise that into a suite of 'test applications' that can be used for acceptance testing, that would also be helpful!

**Comment by Ry10p** [comment]
@freakboy3742  amazing!

That is so cool Google is supporting the project!

A very low priority question; is there any work being done on a Toga-Gtk designer? 

A Toga-Gtk Designer is a project I would LOVE to get into...

Thank you so much,
-Ryan Carl
