### ISSUE TITLE
Error when running setup.py for various platforms

### ISSUE THREAD

**Issue by SableWalnut** [pybee/briefcase#61]
Thanks so much to the developers of this project, I am absolutely loving working with this, just had a little hiccup. 😳

Using macOS Sierra, when I run `python3 setup.py ios -s`, or a setup for any other platform, I get the error as follows:
```
(venv) MacBookPro:beeccc liam$ python3 setup.py ios -s
running ios
 * Writing application template...
Project template: https://github.com/pybee/Python-iOS-template.git
Traceback (most recent call last):
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/cookiecutter/vcs.py", line 129, in clone
    stderr=subprocess.STDOUT,
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'checkout', '3.6']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django',
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/briefcase/app.py", line 336, in run
    self.generate_app_template()
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/briefcase/app.py", line 195, in generate_app_template
    'secret_key': self.secret_key,
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    no_input=no_input,
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/cookiecutter/repository.py", line 84, in determine_repo_dir
    no_input=no_input,
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/cookiecutter/vcs.py", line 132, in clone
    if 'not found' in clone_error.output.lower():
TypeError: a bytes-like object is required, not 'str'
```

I suspect this is because git is failing to clone the cookiecutter for the selected platform. If this is the case, should it perhaps fail more gracefully?

When I try again running the setup.py for ios again I get this:
```
(venv) MacBookPro:beeccc liam$ python3 setup.py ios -s
running ios
 * Writing application template...
Template Python-iOS-template succesfully updated.
Project template: /Users/liam/.cookiecutters/Python-iOS-template
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django',
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/briefcase/app.py", line 336, in run
    self.generate_app_template()
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/briefcase/app.py", line 195, in generate_app_template
    'secret_key': self.secret_key,
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    no_input=no_input,
  File "/Users/liam/apps/beeccc/venv/lib/python3.6/site-packages/cookiecutter/repository.py", line 101, in determine_repo_dir
    '\n'.join(repository_candidates)
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "/Users/liam/.cookiecutters/Python-iOS-template" could not be found in the following locations:
```
Should a check be conducted to ensure the cookiecutter template for the selected platform is correct and/or up to date?

**Comment by SableWalnut** [comment]
# Update

I can see it's failing because the cookiecutter does not yet have a python 3.6 branch, so perhaps that should fail more gracefully, or provide options of which branch to checkout?

**Comment by treyhunner** [comment]
I experienced this same issue. Creating a `python3.5` virtual environment fixed the issue.

It would be wonderful to be able to use this on `python3.6`.

**Comment by eliasdorneles** [comment]
Yeah, I agree, I was thinking maybe we could fallback to previous versions of the support package, and show a warning a message saying that "You're using Python 3.6, which isn't fully supported -- using Python 3.5 support package for now".

**Comment by treyhunner** [comment]
I love the idea of warning the user that 3.6 isn't supported! How could we do that? In `setup.py`? Or do we need some kind of install or import hook?

**Comment by eliasdorneles** [comment]
For just showing the message, one idea would be to list the branches of the remote template repo (using `git ls-remote --heads GIT_REPO_URL`) [here](https://github.com/pybee/briefcase/blob/ab1028ccd73ea39d14f1eee57b91b303b31e2d63/briefcase/app.py#L175), check if the user's Python major / minor version is in the list and show an error if not.

**Comment by capitanjacksparrow** [comment]
Hi, I had the same issue and so I deleted the virtual environment, installed Python 3.5 and repeated the procedure to install briefcase with python 3.5.
However, I still get the same error...any ideas?

**Comment by eliasdorneles** [comment]
@capitanjacksparrow hm, I'd expect everything to work with Python 3.5. Can you try again, taking note of every step (from creating a virtualenv) and then post here these steps that reproduce the error? Thanks!

**Comment by capitanjacksparrow** [comment]
@eliasdorneles thank you very much for you response. I've tried again and in the following I explain to you the detailed steps (sorry for the long message :) ).
I’m working on a iMac, which has jet installed Python2.7, so I’ve installed Python 3.5 and the terminal command to use it is "python3.5" since "python" is already taken by Python2.7.
For the same reason I used "pip3" in all the instructions of the tutorial.
These are the commands list I executed to set up the environment, as indicated in 
https://briefcase.readthedocs.io/en/latest/intro/getting-started.html

I created a directory called BeeWareProjects at a path /myuser_path/ and inside it I executed:
$ mkdir tutorial
$ cd tutorial
$ python3.5 -m venv venv
$ . venv/bin/activate
$ pip3 install briefcase

All these commands ended without any error.
Then I followed the instructions found here (I’m still in the tutorial directory, with the venv activated): 
https://briefcase.readthedocs.io/en/latest/tutorials/tutorial-0.html

$ pip install cookiecutter briefcase
$ cookiecutter https://github.com/pybee/briefcase-template
$ cd helloworld
…update the file helloworld/app.py to return Hello World
$ python setup.py ios -s

[Note: inside the venv I used “pip” and “python” because I checked they are actually Python3.5.
However, I also tried using my pip3 and pyhton3.5 shortcut, but nothing changed]
Here I got the error: 

...
cookiecutter.exceptions.RepositoryNotFound: A valid repository for “/myuser_path/.cookiecutters/Python-iOS-template" could not be found in the following locations:
/myuser_path/.cookiecutters/Python-iOS-template
/myuser_path/.cookiecutters/Python-iOS-template

Any help is really appreciated

**Comment by eliasdorneles** [comment]
Hi @capitanjacksparrow thanks for the detailed steps!
Indeed inside the virtualenv it's best to use just `python` and `pip`! :+1: 

So, I believe you've got a case of a corrupted Git repository under directory `/myuser_path/.cookiecutters/Python-iOS-template`.
Can you try deleting that directory and then try again the same steps?

**Comment by capitanjacksparrow** [comment]
Great...that was the problem! Everything works fine now :)

Thank you very much for your help!

**Comment by eliasdorneles** [comment]
I have a better understanding of this problem now, this is related to https://github.com/pybee/briefcase/issues/76 which partially fixed the problem by doing a `git checkout` for the correct branch when we reuse the cookiecutter template that was already downloaded.

I propose one additional fix checking for the cases of the branch not existing (in the case someone is using Python 3.6 and there is no branch `3.6` yet) or for the branch to be an invalid cookiecutter template (for example, someone creates a version branch from the wrong tree, say, from master), that will do the following:

* run `git fetch` first (to fetch any new branches)
* if the `git checkout` fails, we warn the user about the failure, tell which branch we attempted to checkout and which branches exist, if any
* after doing `git checkout`, we look for a `cookiecutter.json` file in the template directory. If it doesn't exist, we abort execution, telling the user that the repository isn't a valid template, and suggest deleting it

**Comment by isabelapnt** [comment]
I'm working on it.
