### ISSUE TITLE
Handle the case when local cookiecutter template isn't in the correct branch

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/briefcase#76]
When [briefcase runs cookiecutter](https://github.com/pybee/briefcase/blob/9e35f986fbe84aa93ae867c4cf20cdd7a08e7355/briefcase/app.py#L210-L215) it tells it to check out the branch that corresponds to the Python major.minor version being used.

However, cookiecutter does not do that when given the directory path to the git repo, so briefcase should checkout the right branch when [deciding to reuse the local template](https://github.com/pybee/briefcase/blob/9e35f986fbe84aa93ae867c4cf20cdd7a08e7355/briefcase/app.py#L187-L188).

I think it makes sense to do `git checkout BRANCH_NAME` inside of the git_pull() method, just before doing the pull.

**Comment by eliasdorneles** [comment]
Btw, it seems that the problem of not ensuring it's in the right branch is what was causing errors like:

```
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "/home/elias/.cookiecutters/Python-Android-template" could not be found in the following locations:
/home/elias/.cookiecutters/Python-Android-template
```

Which happens because the master branch of the templates isn't a valid template (doesn't have a `cookiecutter.json` file).

**Comment by andrewleech** [comment]
I think this makes a lot of sense and would be especially useful when testing briefcase builds against multiple python versions.  

My only suggestion is ensuring that `git checkout BRANCH_NAME` is _not_ done when `--template` is set at run time for using custom / testing templates. I don't think you were suggesting this at all, I'm just using this setting at the moment so thought of it.

**Comment by eliasdorneles** [comment]
Hm right, that makes sense. :+1:

**Comment by andrewleech** [comment]
I'm pretty sure updating `self.git_pull` or adding the checkout in the place you linked to [(reuse the local template)](https://github.com/pybee/briefcase/blob/9e35f986fbe84aa93ae867c4cf20cdd7a08e7355/briefcase/app.py#L187-L188) would only operated on the default template anyway, any provided on command line wouldn't be touched
